[[ Bug 18277 ]] Translate NSRect <-> MCRectangle correctly
livecode/livecode pull request #4433
Opened 2016-08-30 03:33 UTC by montegoulding

2016-09-30 13:51 UTC, peter-b requested changes

2016-09-30 13:51 UTC, peter-b commented on engine/src/mac-core.mm
> +        get_desktop_height();
I suggest you make `get_desktop_height()` return the desktop height, and make that the only function that accesses the static variables.  Then, for example:

```c++
void MCMacPlatfromMapScreenMCPointToNSPoint(MCPoint p, NSPoint &r_point)
{
    r_point = NSMakePoint(p.x, get_desktop_height() - p.y);
}
```

2016-09-30 21:45 UTC, montegoulding commented on engine/src/mac-core.mm
> +        get_desktop_height();
OK, will do

2016-10-02 23:20 UTC, montegoulding commented
@peter-b Hmm... I had this the other day with Travis timing out. Retrying.

2016-10-03 03:36 UTC, montegoulding commented
@peter-b it seems the retry worked ¯\_(⊙︿⊙)_/¯

2016-11-02 15:41 UTC, peter-b approved these changes
This seems like a reasonable approach.  Do you think caching this data could cause any problems if the screen configuration changes while LiveCode is running?

2016-11-02 21:03 UTC, montegoulding commented on engine/src/mac-core.mm
> +	s_have_desktop_height = false;
@peter-b this ensures that it will be updated after a screen config change

2016-11-02 22:51 UTC, peter-b commented
Looks good to me!
@livecode-vulcan review ok ef1fc00

2016-11-02 22:52 UTC, livecode-vulcan commented
💙 review by @peter-b ok ef1fc0034a9cd62a3226fba22c626dd9693087ea

2016-11-02 23:11 UTC, montegoulding commented
@peter-b before this is merged I'm just wondering if it should be retargeted to `develop-8.1`

2016-11-02 23:12 UTC, peter-b commented
Yes that's probably a good idea.

2016-11-28 09:53 UTC, peter-b commented
@livecode-vulcan review ok f6046d8

2016-11-28 09:55 UTC, livecode-vulcan commented
💙 review by @peter-b ok f6046d85c4575b128d4436c3221b28b8f32110e9

2016-11-28 10:29 UTC, livecode-vulcan commented
😎 test success f6046d85c4575b128d4436c3221b28b8f32110e9

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/640)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/645)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/640)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/644)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/649)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/641)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/641)

2016-11-28 11:25 UTC, merged