Feature java ffi dsl parser
livecode/livecode pull request #4548
Opened 2016-09-22 16:19 UTC by livecodeali

Replaces https://github.com/livecode/livecode/pull/4438

2017-02-23 16:16 UTC, runrevmark commented
@livecode-vulcan review ok 4468582

2017-02-23 16:16 UTC, livecode-vulcan commented
💙 review by @runrevmark ok 4468582e5f1b27b87644b8ae4839c35b087f5997

2017-02-23 16:34 UTC, livecode-vulcan commented
😞 test failure 4468582e5f1b27b87644b8ae4839c35b087f5997

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/998)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1004)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/996)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/997)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1004)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1018)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/995)

2017-02-27 11:42 UTC, peter-b approved these changes

2017-02-27 11:42 UTC, peter-b commented on toolchain/java-dsl-parse/src/LAYOUT.b
> +\t {  }
You need to `AdvanceCurrentPosition(1);` for tab characters, or column numbers will be reported incorrectly when errors occur on lines indented with tabs.

2017-02-27 11:42 UTC, peter-b commented on toolchain/java-dsl-parse/src/DOUBLE_LITERAL.t
> +[0-9]+"."[0-9]+([eE][-+]?[0-9]+)? {
It looks like `1e1` is not parsed as a numeric literal, although it is a numeric literal in LCB.  This isn't necessarily a problem, but it's probably something to be aware of.

2017-02-27 11:44 UTC, peter-b requested changes
Oops, I found one minor issue that I didn't flag up properly earlier.

2017-02-27 11:44 UTC, peter-b commented on toolchain/lc-compile-ffi-java/src/LAYOUT.b
> +\t {  }
You need to `AdvanceCurrentPosition` for tab characters, or the incorrect column number will be reported in error and warning messages.

2017-02-27 11:52 UTC, livecodeali commented on toolchain/lc-compile-ffi-java/src/LAYOUT.b
> +\t {  }
Good catch :-)

2017-02-27 11:55 UTC, peter-b approved these changes

2017-02-27 11:56 UTC, peter-b commented
@livecode-vulcan review ok 5e452a7

2017-02-27 11:56 UTC, livecode-vulcan commented
💙 review by @peter-b ok 5e452a723a2d9b7856c99b09bfb4bae7b7a27035

2017-02-27 12:15 UTC, livecode-vulcan commented
😞 test failure 5e452a723a2d9b7856c99b09bfb4bae7b7a27035

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1003)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1009)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1001)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1002)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1009)
* try-community-win-x86: [failure](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1023)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1000)

2017-02-27 12:26 UTC, peter-b commented
@livecode-vulcan review ok 33f63c2

2017-02-27 12:28 UTC, livecode-vulcan commented
💙 review by @peter-b ok 33f63c2eecfb71fde4d30e59d9803a90948ec522

2017-02-27 12:49 UTC, livecode-vulcan commented
😎 test success 33f63c2eecfb71fde4d30e59d9803a90948ec522

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/1004)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/1010)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/1002)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/1003)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/1010)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/1024)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/1001)

2017-02-27 12:58 UTC, merged