libURLSetStatusCallback no longer requires a target object for the message
livecode/livecode pull request #4565
Opened 2016-09-23 14:33 UTC by trevordevore

Passing an object reference as a second parameter to libURLSetStatusCallback 
is no longer required. If no object is passed in then the message will be sent
to revLibURL itself and you can handle the message anywhere in the message path.

Enhancement request #18470

2016-09-26 15:11 UTC, livecodeali commented on ide-support/revliburl.livecodescript
> +    send tMessage &&  quote & pURL & quote & comma & quote & pStatus & quote to me in 0 milliseconds
@trevordevore It seems like using the 
```
send tMessage && "pUrl, pStatus"
```
form would make sense here too. And perhaps the string could be constructed outside of the if loop to save having it in two places?

2016-09-26 15:48 UTC, peter-b commented on docs/notes/feature-libUrlSetStatusCallback-no-object.md
> +---
Please remove this header!

2016-09-26 15:49 UTC, peter-b requested changes
@trevordevore Like #4561, I've retargeted this at the `develop` branch (LC9) because it changes the API.

Could you please update the documentation for `libURLSetStatusCallback` while you're at it?

2016-09-26 16:13 UTC, trevordevore commented on ide-support/revliburl.livecodescript
> +    send tMessage &&  quote & pURL & quote & comma & quote & pStatus & quote to me in 0 milliseconds
@livecodeali Done.

2016-09-26 16:13 UTC, trevordevore commented
@peter-b I've made the suggested changes.

2016-09-28 13:43 UTC, peter-b commented
@trevordevore I was looking at this again and I noticed something.  If a `pObject` is specified it _must_ be a valid object reference, right? You could use `the paramCount` to help check for invalid object IDs, with something like:

```
on libUrlSetStatusCallback pMessage,pObject
  ##pObject must be a long ID
  ##Allow empty value in which case we use send to self.
  if pMessage is not empty and the paramCount is 1 then
    put pMessage & comma into lvStatusCallback
  else if pMessage is not empty and the paramCount is 2 then
    if not exists(pObject) then
      return "Invalid callback target object" for error
    end if
    put pMessage & comma & pObject into lvStatusCallback
  else
    put empty into lvStatusCallback
  end if
end libUrlSetStatusCallback
```

What do you think about this idea?

2016-09-28 15:15 UTC, trevordevore commented
@peter-b I like the change and have included it.

2016-09-28 15:17 UTC, peter-b approved these changes

2016-09-28 15:18 UTC, trevordevore commented
@peter-b I just modified the case of the error message so that the "i" in "invalid" is lowercase. This seems consistent with other error messages in libURL.

2016-09-28 15:31 UTC, peter-b commented on docs/dictionary/command/libURLSetStatusCallback.lcdoc
> +backscript, or library stack.
@trevordevore I'm really sorry, but I missed this: I think this needs to be changed from:

> If <messageName> is not empty but <objectLongIDE> is empty

to:

> If <messageName is not empty and <objectLongID> is not specified

in order to match my suggested changes to how `libURLSetStatusCallback` handles the arguments.

I'm sorry for not spotting this earlier! 😞

2016-09-28 15:38 UTC, trevordevore commented on docs/dictionary/command/libURLSetStatusCallback.lcdoc
> +backscript, or library stack.
@peter-b Updated.

2016-09-28 16:20 UTC, peter-b commented
@trevordevore This is good, thank you. 👍 

@livecode-vulcan review ok c6ea510

2016-09-28 16:22 UTC, livecode-vulcan commented
💙 review by @peter-b ok c6ea510b14c02b724b6720e19364cd6e92df4cc8

2016-09-28 16:43 UTC, livecode-vulcan commented
😎 test success c6ea510b14c02b724b6720e19364cd6e92df4cc8

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/302)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/307)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/302)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/302)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/308)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/302)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/302)

2016-09-29 07:25 UTC, merged