Bugfix 15865
livecode/livecode pull request #4611
Opened 2016-10-04 17:06 UTC by bhall2001

fixed description to correctly state that is not among implies string
does not exist.

2016-10-06 12:55 UTC, livecodeali requested changes

2016-10-06 12:55 UTC, livecodeali commented on docs/notes/bugfix-15865
> +# Fixed Dictionary example for is within
@bhall2001 I think you've used the same bugfix note description as for the other PR!

Also, could you make sure the file has a `.md` suffix please?

2016-10-07 15:25 UTC, livecodeali approved these changes

2016-10-07 15:25 UTC, livecodeali commented
@livecode-vulcan review ok fb329e6

2016-10-07 15:26 UTC, livecode-vulcan commented
💙 review by @livecodeali ok fb329e6a4a23913cd64b73b4e8f1f5fcca243549

2016-10-07 15:53 UTC, livecode-vulcan commented
😎 test success fb329e6a4a23913cd64b73b4e8f1f5fcca243549

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/376)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/381)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/376)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/376)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/382)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/376)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/376)

2016-10-09 22:45 UTC, merged