[Bug 18579] Support defaultNetworkInterface in accept
livecode/livecode pull request #4751
Opened 2016-10-12 20:40 UTC by montegoulding

Note that the `[{ with | without } verification]` clause is broken (never finished being implemented):
- always false
- doesn't actually do anything in MCS_accept

It is not actually documented for the accept command either so I'm not really sure what it's doing there. Anyway, I decided not to touch that for the time being...

2016-10-12 20:44 UTC, peter-b commented
@montegoulding Just to clarify, are you saying that `open secure socket ... with verification` currently doesn't actually do any verification?

2016-10-12 20:45 UTC, montegoulding commented
No, I'm talking about `accept` only here. I haven't investigated `open`.

2016-10-12 20:46 UTC, peter-b commented
@montegoulding Ah, that's (potentially) not such a serious problem.  Last time I checked, `accept secure socket` ignored the `secure` -- there's already a bug open about that.

2016-10-12 20:50 UTC, montegoulding commented
Ah... yeah that at least gets to `MCS_accept` correctly but nothing is done with it there

2016-10-13 08:44 UTC, peter-b requested changes
I spotted a couple of places where invalid port numbers get silently truncated. Other than that, this looks great.

2016-10-13 08:44 UTC, peter-b commented on engine/src/cmdse.cpp
> +		MCNetworkExecAcceptDatagramConnectionsOnPort(ctxt, uint16_t(t_port), *t_message);
Please add a check that `t_port` is within the valid range and fail if not.

2016-10-13 08:44 UTC, peter-b commented on engine/src/socket_resolve.cpp
> +	r_addr->sin_port = MCSwapInt16HostToNetwork(uint16_t(port));
Port needs to be checked for valid range here too (well, actually, probably above near the `MCNumberFetchAsInteger()` call).  Should handle an out-of-range port in the same way as an unrecognised named port.

2016-10-13 09:03 UTC, montegoulding commented on engine/src/socket_resolve.cpp
> +	r_addr->sin_port = MCSwapInt16HostToNetwork(uint16_t(port));
OK, yes that's a good idea

2016-10-13 09:28 UTC, peter-b approved these changes

2016-10-13 09:28 UTC, peter-b commented
@livecode-vulcan review ok e190ee7

2016-10-13 09:31 UTC, livecode-vulcan commented
💙 review by @peter-b ok e190ee7b168259c794bfc224aec61c051ae229e7

2016-10-13 09:53 UTC, montegoulding commented
hmm... broke something...

2016-10-13 09:53 UTC, livecode-vulcan commented
😎 test success e190ee7b168259c794bfc224aec61c051ae229e7

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/422)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/427)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/422)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/422)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/428)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/422)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/422)

2016-10-13 10:24 UTC, peter-b commented
@livecode-vulcan review ok ce0c326

2016-10-13 10:24 UTC, livecode-vulcan commented
💙 review by @peter-b ok ce0c326c16b73b6ff2ecd4482df07340543cbae8

2016-10-13 10:46 UTC, livecode-vulcan commented
😎 test success ce0c326c16b73b6ff2ecd4482df07340543cbae8

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/424)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/429)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/424)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/424)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/430)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/424)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/424)

2016-10-13 19:21 UTC, merged