[Docs] Command Syntax and Parameter fixes - 4
livecode/livecode pull request #4783
Opened 2016-10-18 19:47 UTC by seaniepie

2016-10-18 19:50 UTC, seaniepie commented
@montegoulding , This is the last of the command fixes for TravisCL. There's just a mammoth amount of 'property' items and a few 'functions' to go. Doing functions first

2016-10-20 08:48 UTC, livecodeali requested changes

2016-10-20 08:48 UTC, livecodeali commented on docs/dictionary/command/resolve-image.lcdoc
> +
Could you make these parameters camel case please?

2016-10-20 16:05 UTC, seaniepie commented on docs/dictionary/command/resolve-image.lcdoc
> +
Done. 👍

2016-10-20 16:05 UTC, seaniepie commented
Done 👍

2016-10-20 16:19 UTC, livecodeali commented on docs/dictionary/command/resolve-image.lcdoc
> +
Sorry, can you do `idOrName` as well?

2016-10-20 18:07 UTC, livecodeali commented
@livecode-vulcan review ok 66283e5

2016-10-20 18:07 UTC, livecodeali approved these changes

2016-10-20 18:09 UTC, livecode-vulcan commented
💙 review by @livecodeali ok 66283e5d397f1588dd2e96a6dc9fdef1f83b5480

2016-10-20 18:33 UTC, livecode-vulcan commented
😎 test success 66283e5d397f1588dd2e96a6dc9fdef1f83b5480

* try-community-linux-x86: [success](https://vulcan.livecode.com/builders/try-community-linux-x86/builds/462)
* try-community-mac: [success](https://vulcan.livecode.com/builders/try-community-mac/builds/467)
* try-community-linux-x86_64: [success](https://vulcan.livecode.com/builders/try-community-linux-x86_64/builds/462)
* try-community-emscripten: [success](https://vulcan.livecode.com/builders/try-community-emscripten/builds/462)
* try-community-ios: [success](https://vulcan.livecode.com/builders/try-community-ios/builds/468)
* try-community-win-x86: [success](https://vulcan.livecode.com/builders/try-community-win-x86/builds/462)
* try-community-android-armv6: [success](https://vulcan.livecode.com/builders/try-community-android-armv6/builds/462)

2016-10-20 19:41 UTC, merged