Update libgraphics to account for Skia API changes
livecode/livecode pull request #5269
Opened 2017-03-13 14:31 UTC by livecodeali

The biggest impact is the removal of custom blend modes in Skia. This
forces us to drop support for legacy blend modes as we can no longer
emulate them.

On the plus side, only using the built-in Skia blend modes will result
in faster blending.

(cherry picked from commit 2ffc8ef900168f5ce0d791b9d6b72d3273a50dc6)

2017-03-16 20:39 UTC, livecodeian requested changes

2017-03-16 20:39 UTC, livecodeian commented on libgraphics/src/context.cpp
> +		self->layer->canvas->drawImage(t_image, t_child_layer->origin_x, t_child_layer->origin_y, &t_paint);
Could this be used instead? http://skia-doc.commondatastorage.googleapis.com/doxygen/doxygen/html/classSkSurface.html#a788d7e9a9eb7e93aef3dce9f684ea09f

2017-03-16 20:39 UTC, livecodeian commented on libgraphics/src/context.cpp
> +			//t_stipple = new (nothrow) SkStippleMaskFilter();
If the stipple filter is no longer available then I suggest removing this code along with kMCPaintStyleStippled

2017-03-16 20:39 UTC, livecodeian commented on libgraphics/src/w32text.cpp
> +			if (false && ((*t_context_pxl >> 24) & 0xFF) == 0xFF)
Should this dead code be removed?

2017-03-16 20:39 UTC, livecodeian commented on libgraphics/src/w32text.cpp
> +		if (true || (*t_context_pxls >> 24) != 0xff)
Can this if be removed now?

2017-03-16 23:59 UTC, livecodefraser commented on libgraphics/src/w32text.cpp
> +			if (false && ((*t_context_pxl >> 24) & 0xFF) == 0xFF)
The dead code gets removed in the update to use DirectWrite instead of GDI text rendering.

2017-03-17 00:00 UTC, livecodefraser commented on libgraphics/src/context.cpp
> +		self->layer->canvas->drawImage(t_image, t_child_layer->origin_x, t_child_layer->origin_y, &t_paint);
Unfortunately, the resetMatrix bit is required - I did try it that way before and it caused issues.

2017-03-17 09:57 UTC, livecodeian commented on libgraphics/src/context.cpp
> +		self->layer->canvas->drawImage(t_image, t_child_layer->origin_x, t_child_layer->origin_y, &t_paint);
The resetMatrix stuff is fine, but the docs for SkSurface::draw implies that it could be more efficient than snapshot followed by drawImage

2017-03-17 10:14 UTC, livecodeian commented on engine/src/mblandroidtypeface.cpp
> +    t_typeface->ref();
looks like there's a convenience function for this - sk_ref_sp(T* obj) which wraps the ptr and increments the ref count

2017-05-12 09:14 UTC, livecodeian commented
@livecode-vulcan review ok db257d5

2017-05-12 09:16 UTC, livecode-vulcan commented
💙 review by @livecodeian ok db257d5bbdbea99a186e8d768634e5a151ebe5a1

2017-05-12 09:19 UTC, merged