Bugfix 15565
livecode/livecode pull request #5478
Opened 2017-05-17 14:48 UTC by alexbrisan

I have added the following (i.e. these are now accepted statements)

create card .. in stack ...
create control ... in card ... 

where the stack and card are not the default stack/card

2017-05-17 14:49 UTC, runrevmark commented on engine/src/card.h
> +	MCCard *clone(Boolean attach, Boolean controls, MCStack *p_parent=nullptr);
Missing spaces around '='

2017-05-17 14:52 UTC, alexbrisan commented on engine/src/card.h
> +	MCCard *clone(Boolean attach, Boolean controls, MCStack *p_parent=nullptr);
Fixed

2017-05-17 14:57 UTC, runrevmark commented on engine/src/exec-interface.cpp
> +MCControl* MCInterfaceExecCreateControlGetObject(MCExecContext& ctxt, int p_type, MCObject *&r_parent)
I don't think the r_parent var is used - if not, we can remove it.

2017-05-17 16:26 UTC, runrevmark commented on engine/src/exec-interface.cpp
> +    MCStack *t_current_stack;
We try not to leave POD-typed vars (those which do not have a constructor) uninit'd on declaration. I'd suggest:
```
MCStack *t_current_stack = p_container == nullptr ? MCdefaultstackptr : p_container->getstack()
```

2017-05-17 16:27 UTC, runrevmark commented on tests/lcs/core/interface/stack.livecodescript
> +on TestStackLockedness
I suggest TestCreateControlInContainerWithDefaultStackLocked

2017-05-17 16:28 UTC, runrevmark commented
@alexbrisan The same bug is present in CreateWidget too - they are the same bug, so fix them as part of 19703.

2017-05-17 16:28 UTC, livecodeali requested changes

2017-05-17 16:28 UTC, livecodeali commented on docs/dictionary/command/create-card.lcdoc
> +a stackName, it is placed in defaultStack.
This is probably better as `in the defaultStack`. Also, if you put `<defaultStack>` that creates a link to the defaultStack entry in the docs.

2017-05-17 16:28 UTC, livecodeali commented on docs/dictionary/command/create-card.lcdoc
> +in defualtStack When the <card> is created, you go to the new <card>.
`... in the <defaultStack>. When..`

2017-05-17 16:28 UTC, livecodeali commented on docs/dictionary/command/create.lcdoc
> +Syntax: create [invisible] <objectType> [<objectName>] [in <group>] [in <card>]
This should be either/or, so 
`[in {group | card}]`

2017-05-17 16:28 UTC, livecodeali commented on docs/dictionary/command/create.lcdoc
> +don't specify either a group nor a card, the object is created on the
maybe `specify neither a group nor a card`, rather than `don't specify either...`

2017-05-17 16:28 UTC, runrevmark commented on docs/dictionary/command/create-card.lcdoc
> +Syntax: create card [<cardName>] [in stack <stackName>]
The additional syntax should be `[in <stack>]`

2017-05-17 16:30 UTC, runrevmark commented on docs/dictionary/command/create-card.lcdoc
> +stackName:
```
stack:
...
```
Use a similar description as for <group> in the other doc.

2017-05-17 23:31 UTC, montegoulding commented
@alexbrisan This is going to be _really_ helpful! 💯 

Bikeshed: I suspect I would more naturally write `on card | stack` instead of `in` as with groups. Of course it's probably better to stick to one form and we already use `in`.

2017-05-18 09:53 UTC, livecodeali commented on docs/dictionary/command/create.lcdoc
> +Syntax: create [invisible] <objectType> [<objectName>] [in <group>] [in <card>]
Sorry, I gave you bad advice here - it needs to be 
`[in {<group> | <card>}]` as things that are parameters to the syntax have to be enclosed in `<>`

2017-05-18 12:48 UTC, livecodeali commented
@alexbrisan Two additional things I've just noticed! (sorry)
- The `MCGroup *` cast should be removed from `MCInterfaceExecCreateControl(ctxt, *t_new_name, otype, (MCGroup *)parent, visible == False);`

2017-05-18 13:28 UTC, livecodeali approved these changes

2017-05-18 13:28 UTC, livecodeali commented
@livecode-vulcan review ok 48f8ae0

2017-05-18 13:29 UTC, livecode-vulcan commented
💙 review by @livecodeali ok 48f8ae021c812d94b543c1d85ed28570d3b1f548

2017-05-18 14:01 UTC, livecode-vulcan commented
😞 test failure 48f8ae021c812d94b543c1d85ed28570d3b1f548

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/254)
* try-community-armv6-android-api9: [failure](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/263)
* try-community-js-emscripten-sdk1.35: [failure](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/243)
* try-community-universal-ios-iphoneos10.3: [failure](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/186)
* try-community-universal-ios-iphonesimulator10.3: [failure](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/186)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/252)
* try-community-universal-mac-macosx10.9: [failure](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/257)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/256)
* try-community-x86-linux-debian8: [failure](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/261)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/256)
* try-community-x86_64-linux-debian8: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/261)
* try-community-x86-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/280)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/251)

2017-05-18 18:03 UTC, runrevmark commented
@alexbrisan : Could you add a test for 'create widget' too - as the codepaths are different in the engine... Hopefully @livecodeali can advise how to make sure the test environment has a widget to try and create :)

2017-05-23 09:30 UTC, runrevmark commented on tests/lcs/core/interface/stack.livecodescript
> +	TestAssert "test if the widget was created in the correct card", there is a widget "My Navbar" of card "Other"
use 'of stack "Temp"' here to make sure it is entirely unambiguous

2017-05-23 10:03 UTC, runrevmark commented
@livecode-vulcan review ok 1af86eb

2017-05-23 10:04 UTC, livecode-vulcan commented
💙 review by @runrevmark ok 1af86ebfa128ce62722c1385bcf91729349b907c

2017-05-23 10:43 UTC, livecode-vulcan commented
😞 test failure 1af86ebfa128ce62722c1385bcf91729349b907c

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/269)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/278)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/258)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/201)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/201)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/267)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/272)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/271)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/276)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/271)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/276)
* try-community-x86-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/295)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/266)

2017-05-24 14:07 UTC, livecodealex commented
@livecode-vulcan retry

2017-05-25 14:27 UTC, livecodealex commented
@livecode-vulcan retry

2017-05-25 16:20 UTC, livecodepanos commented
@livecode-vulcan retry 1af86eb

2017-05-25 17:16 UTC, livecode-vulcan commented
😞 test failure 1af86ebfa128ce62722c1385bcf91729349b907c

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/289)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/295)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/275)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/218)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/218)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/284)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/289)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/287)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/293)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/287)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/293)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/312)
* try-community-x86_64-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/284)

2017-05-25 17:37 UTC, livecodepanos commented
@livecode-vulcan retry 1af86eb

2017-05-25 19:09 UTC, livecode-vulcan commented
😎 test success 1af86ebfa128ce62722c1385bcf91729349b907c

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/291)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/297)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/277)
* try-community-universal-ios-iphoneos10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos10.3/builds/220)
* try-community-universal-ios-iphonesimulator10.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator10.3/builds/220)
* try-community-universal-mac-macosx10.6: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/286)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/291)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/289)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/295)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/289)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/295)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/314)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/286)

2017-05-25 20:21 UTC, merged