[[ Bugfix 20951 ]] Fixed bug causing garbage at end of repeat to be ignored
livecode/livecode pull request #6317
Opened 2018-02-05 14:58 UTC by livecodealex

2018-02-05 15:59 UTC, livecodeali requested changes

2018-02-05 15:59 UTC, livecodeali commented on tests/lcs/parser/repeat.parsertest
> +%EXPECT_PASS
this needs to be `%EXPECT PASS` (no underscore)

2018-02-05 15:59 UTC, livecodeali commented on tests/lcs/parser/repeat.parsertest
> +%EXPECT_PASS
same here

2018-02-05 15:59 UTC, livecodeali commented on tests/lcs/parser/repeat.parsertest
> +%SUCCESS
This needs to be 
```
%EXPECT PASS
%ERROR PE_REPEAT_BADCOND AT AFTER_ENDVALUE
```

(and rename your label from ALEX to AFTER_ENDVALUE, just so it is more instructive of the intended position). You can still include alex in your garbage if you want, just do it as
```
repeat with i = 1 to 10 %{AFTER_ENDVALUE} alex 10
```
:-)

2018-02-05 16:28 UTC, livecodealex commented
@livecodeali Should be fixed now

2018-02-05 16:29 UTC, livecodeali commented on tests/lcs/parser/repeat.parsertest
> +%SUCCESS
This bit is still not quite right:
```
%EXPECT PASS
%ERROR PE_REPEAT_BADCOND AT AFTER_ENDVALUE
```

2018-02-05 16:30 UTC, livecodealex commented
@livecodeali now?

2018-02-05 16:31 UTC, livecodeali commented
@livecodealex there shouldn't be a `%SUCCESS` on that one

2018-02-05 16:32 UTC, livecodeali commented
Sorry, I didn't make that at all clear originally

2018-02-05 16:39 UTC, livecodeali approved these changes

2018-02-05 17:48 UTC, livecodealex commented
As @runrevmark nicely pointed out, this is probably failing due to the fact that the IDE tests cannot run. I wonder what we should do in this situation...

2018-02-05 20:42 UTC, livecodeali commented
Ah! Well, it probably makes sense to submit a PR fixing the bits in the IDE (this can go into any branch - probably 8.1) and then once it is merged up we can trigger Travis to run again

2018-02-12 09:21 UTC, livecodealex commented
@livecodeali on it

2018-02-12 11:11 UTC, livecodealex commented
Testing depends on https://github.com/livecode/livecode-ide/pull/1910

2018-04-18 08:19 UTC, livecodeali commented
@livecode-vulcan review ok a9ad5d2

2018-04-18 08:21 UTC, livecode-vulcan commented
💙 review by @livecodeali ok a9ad5d2f01c001b2b41be8102d86e2511e35ea7f

2018-04-18 10:25 UTC, livecode-vulcan commented
😞 test failure a9ad5d2f01c001b2b41be8102d86e2511e35ea7f

* try-community-armv6-android-api8: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api8/builds/1422)
* try-community-armv6-android-api9: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-api9/builds/1438)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1412)
* try-community-universal-ios-iphoneos11.3: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.3/builds/15)
* try-community-universal-ios-iphonesimulator11.3: [failure](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.3/builds/15)
* try-community-universal-mac-macosx10.6: [failure](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.6/builds/1416)
* try-community-universal-mac-macosx10.9: [failure](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1442)
* try-community-x86-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian7/builds/1422)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1436)
* try-community-x86_64-linux-debian7: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian7/builds/1421)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1431)
* try-community-x86-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1472)
* try-community-x86_64-win32: [pending](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1412)

2019-03-07 10:15 UTC, livecodepanos commented
@livecode-vulcan retry a9ad5d2

2019-03-07 11:43 UTC, livecode-vulcan commented
😎 test success a9ad5d2f01c001b2b41be8102d86e2511e35ea7f

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/303)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/295)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/295)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/295)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/295)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1817)
* try-community-universal-ios-iphoneos12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.1/builds/45)
* try-community-universal-ios-iphonesimulator12.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.1/builds/45)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1848)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1838)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1837)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1871)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1812)

2019-03-07 12:17 UTC, merged