[[ PlayerPanning ]] Add stereo balance & panning properties to mac player
livecode/livecode pull request #6603
Opened 2018-07-03 17:12 UTC by livecodeian

2018-07-04 08:45 UTC, montegoulding requested changes
Hi @livecodeian just a few tweaks to the docs

2018-07-04 08:45 UTC, montegoulding commented on docs/dictionary/property/audioPan.lcdoc
> +Introduced: 9.0.1
@livecodeian Can you add `Associations: player` to the doc

2018-07-04 08:45 UTC, montegoulding commented on docs/dictionary/property/leftBalance.lcdoc
> +
Again `Associations: player`

2018-07-04 08:45 UTC, montegoulding commented on docs/dictionary/property/audioPan.lcdoc
> +Use the audioPan property to pan audio from the left & right channels to the other.
@livecodeian I'm wondering about:
`Use the audioPan property to pan audio from either the left or right channel to the other.`

2018-07-04 08:45 UTC, montegoulding commented on docs/dictionary/property/audioPan.lcdoc
> +Important:
@livecodeian this should be block quote with bold Important:

```
>**Important:** This property only has an effect on media files that contain stereo audio tracks.
> Mono audio tracks cannot currently be panned.
```

2018-07-04 08:45 UTC, montegoulding commented on docs/dictionary/property/leftBalance.lcdoc
> +Important:
@livecodeian see note about this being a block quote above

2018-07-04 08:45 UTC, montegoulding commented on docs/dictionary/property/rightBalance.lcdoc
> +Important:
@livecodeian ditto association and block quote

2018-07-04 08:45 UTC, montegoulding commented on docs/notes/feature-player-pan-mac.md
> +# New stereo panning properties added to MacOSX Player object
Probably not worth worrying about but we should use `macOS`

2018-07-04 10:25 UTC, montegoulding commented
@livecode-vulcan review ok dca90c9

2018-07-04 10:27 UTC, livecode-vulcan commented
💙 review by @montegoulding ok dca90c93065730c559233f459b13baabc0dceaca

2018-07-04 10:28 UTC, montegoulding commented
@livecode-vulcan review not ok dca90c9

@livecodepanos found a crash

2018-07-04 10:28 UTC, livecode-vulcan commented
💔 review by @montegoulding not ok dca90c93065730c559233f459b13baabc0dceaca

2018-07-04 20:43 UTC, montegoulding requested changes
@livecodeian sorry I missed that crash. I've just found one more little tweak which looks like a potential crash to me.

2018-07-04 20:43 UTC, montegoulding commented on engine/src/mac-av-player.mm
> +	t_error = MTAudioProcessingTapCreate(kCFAllocatorDefault, &t_callbacks, kMTAudioProcessingTapCreationFlag_PostEffects, &t_tap);
@livecodeian we should check t_error here and return false on an error then check it below. At the moment we could be setting r_tap to the uninitialised t_tap here and calling CFRelease on it

2018-07-05 11:06 UTC, montegoulding commented
@livecode-vulcan review ok 677392a

2018-07-05 11:07 UTC, montegoulding approved these changes

2018-07-05 11:08 UTC, livecode-vulcan commented
💙 review by @montegoulding ok 677392a6da92d0fd4938f4d924c02c6bde21b8c9

2018-07-05 12:17 UTC, livecode-vulcan commented
😎 test success 677392a6da92d0fd4938f4d924c02c6bde21b8c9

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/30)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/22)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/22)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/22)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/22)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1544)
* try-community-universal-ios-iphoneos11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos11.4/builds/71)
* try-community-universal-ios-iphonesimulator11.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator11.4/builds/71)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1574)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1568)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1564)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1601)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1541)

2018-07-05 12:17 UTC, merged