[Dctionary] read from file to reset
livecode/livecode pull request #6747
Opened 2018-10-19 10:09 UTC by livecodesam

command/read-from-file.lcdoc - Fixed broken links.
keyword/real4.lcdoc - Fixed broken link.
keyword/real8.lcdoc - Fixed broken link.
command/record-pause.lcdoc - Fixed broken link.
command/record-resume.lcdoc - Fixed broken link.
command/record-sound.lcdoc - Fixed broken link. Added missing references.
glossary/r/record-set.cldoc - Fixed broken link.
function/recordCompressionTypes.lcdoc - Reformatted list items. 
property/recordFormat.lcdoc - Fixed broken link.
property/recordInput.lcdoc - Reformatted list items. Added missing references.
property/rectangle.lcdoc - Reformatted list items.
property/relayerGroupedControls.lcdoc - Fixed broken link.
message/reloadStack.lcdoc - Fixed broken link.
command/remove-script.lcdoc - Fixed broken link.
property/repeatRate.lcdoc - Fixed broken link.
command/reply.lcdoc - Fixed broken link. Added non-breaking space in hope this would cause the `<string>` before it to be displayed in the same way as the others.
command/request.lcdoc - Removed extraneous html markdown from external link.
command/reset.lcdoc - Removed extraneous html(?).

2018-10-19 13:33 UTC, livecodepanos commented on docs/dictionary/command/reply.lcdoc
> +    reply <string> &nbsp;
@livecodesam the `&nbsp;` does not seem to make any difference. I suggest just to remove the `<>` (e.g. replace all 4 occurrences of `<string>` with `string` in this section

2018-10-22 15:37 UTC, seaniepie requested changes
Just a few suggestions for these docs if you don't mind. I hope they make sense.

2018-10-22 15:37 UTC, seaniepie commented on docs/dictionary/command/record-sound.lcdoc
> +> form of the play <command>.
Can we add angle brackets around the word 'play' and add a reference to 'play (command)'.

2018-10-22 15:37 UTC, seaniepie commented on docs/dictionary/command/record-sound.lcdoc
> +dontUseQT (property), dontUseQTEffects (property),
add 'play (command),' here

2018-10-22 15:37 UTC, seaniepie commented on docs/dictionary/command/reply.lcdoc
> +    reply <string> &nbsp;
Does using the escape character (' \\ ') make a difference?

> `reply \<string\>`

2018-10-22 15:37 UTC, seaniepie commented on docs/dictionary/command/request.lcdoc
> +at http://developer.apple.com/techpubs/mac/IAC/IAC-2.html
Putting the link in parenthesis directly after the original in square brackets creates a link, thus:
> \[http://developer.apple.com/techpubs/mac/IAC/IAC-2.html](http://developer.apple.com/techpubs/mac/IAC/IAC-2.html)

Better still, use a simplified version in the square brackets such as:

> located on \[Apple's developer site](http:....)

Additionally, all http references should now be https unless this does not exist based on current best practice.
Further still, the above link does not work anymore! [This page](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DistrObjects/DistrObjects.html) states that the old way is no longer used. Perhaps this link would be better for now:
https://developer.apple.com/documentation/coreservices/apple_events

2018-10-22 15:37 UTC, seaniepie commented on docs/dictionary/command/reset.lcdoc
> +> settings as objects you create in a standalone application.
This whole document could do with reference peppering.
- 32, Properties, template, objects
- 33, objects
- 35, template
- 36, objects x3
- 38, objects & standalone application

2018-10-22 15:37 UTC, seaniepie commented on docs/dictionary/function/recordCompressionTypes.lcdoc
> +- the codec's four: character identifier
Is the colon required here?

2018-10-22 15:37 UTC, seaniepie commented on docs/dictionary/property/recordInput.lcdoc
> +dontUseQT (property), dontUseQTEffects (property),
Need to add QuickTime reference here too

2018-10-22 15:37 UTC, seaniepie commented on docs/dictionary/property/recordInput.lcdoc
Is it possible to put an alternative here or specifically state that there is no way to set a recordInput from LCv8.1 just to make it absolutely clear? (We may have to go through all references to QT stuff later and do the same).

2018-11-02 10:07 UTC, livecodepanos commented
@livecode-vulcan review ok cb1c315

2018-11-02 10:07 UTC, livecode-vulcan commented
💙 review by @livecodepanos ok cb1c315ca8fdf183273be805819e5747e0871524

2018-11-02 10:18 UTC, livecodepanos commented
@livecodesam @seaniepie Thank you for the PR and the comments.

I have marked it as reviewed since the basic purpose of this series of PRs that @livecodesam submits is to restore any missing information, such as fixing broken links or fixing malformed text.

Of course there is still room for improvement in the docs (for example changing the wording, adding more examples, more references etc). In this case I suggest submitting new PRs, as this is more easily manageable from our point of view.

2018-11-02 13:08 UTC, livecode-vulcan commented
😎 test success cb1c315ca8fdf183273be805819e5747e0871524

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/183)
* try-community-armv7-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-sdk26_ndk16r15/builds/175)
* try-community-arm64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-sdk26_ndk16r15/builds/175)
* try-community-x86-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-sdk26_ndk16r15/builds/175)
* try-community-x86_64-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-sdk26_ndk16r15/builds/175)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/1697)
* try-community-universal-ios-iphoneos12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos12.0/builds/79)
* try-community-universal-ios-iphonesimulator12.0: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator12.0/builds/79)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/1727)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/1720)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/1717)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/1753)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/1694)

2018-11-05 10:55 UTC, merged