[[TreeView Widget]] Mobile Support Enhancements [WIP]
livecode/livecode pull request #7154
Opened 2019-08-31 02:35 UTC by bwmilby

General enhancements to the TreeView Widget that support use on the mobile platform and for use as a menu.

* Ability to customize font
* Ability to customize row height
* Ability to trim leading characters from key (to support custom sorting)
* Property/messages necessary to support mobile scroller
* Ability to disable hover
* Save `alternate row backgrounds` property
* Ability to set icon size (height)
* Improve key/value trimming logic (less extra space on right side of widget)
* When `readOnly`, only save space for one icon on right

- [ ] Need to add bug fix/enhancement note

2019-08-31 02:36 UTC, bwmilby commented
@livecodeali This is the code that we discussed at the conference.

2019-09-30 09:44 UTC, livecodeali requested changes

2019-09-30 09:44 UTC, livecodeali commented on extensions/widgets/treeview/treeview.lcb
> +	put the size of my font + 8 into tRowHeight
Could you make this a `constant kRowTextPadding is 4` and then `the size of my font + 2 * kRowTextPadding into tRowHeight` - i suppose it's something that might become a property itself at some stage

2019-09-30 09:44 UTC, livecodeali commented on extensions/widgets/treeview/treeview.lcb
> +				if the number of chars in tKeyDisplay < mCharsToTrimFromKey then
You might as well make this a `<=` as it will be slightly more efficient to replace the value with the empty string than delete all its chars

2019-09-30 09:44 UTC, livecodeali commented on extensions/widgets/treeview/treeview.lcb
> +		throw "Leading Characters to Trim From Key must be >= 0"
perhaps `number of leading characters to trim from key must be non-negative`? I think the convention here is the we do not capitalise error messages used with `throw` (although there are some in this file that are initially capitalised)

2019-09-30 09:44 UTC, livecodeali commented on extensions/widgets/treeview/treeview.lcb
> +based on the currently selected font and size.
There's something up with the commit here - I guess you maybe put the bug fix and test changes into a different one?

2019-09-30 09:45 UTC, livecodeali commented
@bwmilby This looks great - there's just a few minor things plus the issue with the missing bugfix / test from f2facb5a2518371e9e3b37924d605f5a133f4a08

2019-10-03 20:46 UTC, bwmilby commented on extensions/widgets/treeview/treeview.lcb
> +	put the size of my font + 8 into tRowHeight
Added in 10/3 commit

2019-10-03 20:47 UTC, bwmilby commented on extensions/widgets/treeview/treeview.lcb
> +				if the number of chars in tKeyDisplay < mCharsToTrimFromKey then
Changed in 10/3 commit

2019-10-03 20:49 UTC, bwmilby commented on extensions/widgets/treeview/treeview.lcb
> +		throw "Leading Characters to Trim From Key must be >= 0"
Fixed in 10/3 commit (also made other throw's lower case)

2019-10-03 20:54 UTC, bwmilby commented on extensions/widgets/treeview/treeview.lcb
> +based on the currently selected font and size.
The bug never made it to a release version.  I had split off to a new branch for these updates and discovered/fixed the bug.  I went back to the original PR and fixed it there before it was merged in.  I probably should should have done it as a separate commit on this branch, but had forgotten about it when I was doing my cherry pick.

2019-10-03 20:59 UTC, bwmilby commented on extensions/widgets/treeview/treeview.lcb
> +based on the currently selected font and size.
The bug was fixed in PR #6994 prior to 9.5 release

2019-10-03 21:04 UTC, bwmilby commented
PR #6994 is where the missing code is from https://github.com/livecode/livecode/commit/f2facb5a2518371e9e3b37924d605f5a133f4a08

2019-11-26 23:03 UTC, bwmilby commented
I think this would be good to be merged into 9.6.0 since it is a mobile targeted enhancement.  I'm not sure what else I can to for this to satisfy the "change requested" flag though.

2019-11-27 16:21 UTC, livecodeali commented
@bwmilby Sorry about that - was a bit confused about f2facb5 - I think it just has an incorrect commit message then? 
```
[Tree View Widget] Clear hilitedElement bug fix 
If no element was selected, setting the hilitedElement to empty would
throw an error.  Added an additional test to ensure that the widget did
not attempt to unselect and empty path.
```
The content of the commit seems to be a fix to the `textHeight` docs

2019-11-27 16:22 UTC, livecodeali commented
@bwmilby Actually ignore that - I think I will just squash merge the PR as it's all just in one file

2019-11-27 16:22 UTC, livecodeali commented
@livecode-vulcan review ok e7e96e9

2019-11-27 16:25 UTC, livecode-vulcan commented
💙 review by @livecodeali ok e7e96e9b518bd933b260a6fc8e926a576d5b5919

2019-11-27 16:50 UTC, livecode-vulcan commented
😞 test failure e7e96e9b518bd933b260a6fc8e926a576d5b5919

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/682)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/91)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/91)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/91)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/91)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2208)
* try-community-universal-ios-iphoneos13.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.1/builds/42)
* try-community-universal-ios-iphonesimulator13.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.1/builds/42)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2237)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2224)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2223)
* try-community-x86-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2257)
* try-community-x86_64-win32: [failure](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2197)

2019-11-27 16:58 UTC, livecodeali commented
@bwmilby The build is complaining about the lack of docs for `scroll` because you've sort of combined the `viewTopPosition` and `scroll` properties - is there a need for the `viewTopPosition` synonym?

2019-11-27 21:23 UTC, bwmilby commented
Strictly there isn't a need for the synonym.  Initially I think I just exported the internally used variable name to make is accessible and added the synonym to be consistent with other controls.  I can do a commit to remove it.

2019-11-27 22:37 UTC, livecodeali commented
Cool yeah I think it should be fine just to use `scroll` (and therefore also `vScroll`)

2019-11-28 08:58 UTC, livecodeali commented
@livecode-vulcan review ok 5f0c31f

2019-11-28 09:02 UTC, livecode-vulcan commented
💙 review by @livecodeali ok 5f0c31fcf978220fc911b849a002e9a059ef87cd

2019-11-28 09:26 UTC, livecode-vulcan commented
😎 test success 5f0c31fcf978220fc911b849a002e9a059ef87cd

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/683)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/92)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/92)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/92)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/92)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2209)
* try-community-universal-ios-iphoneos13.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.1/builds/43)
* try-community-universal-ios-iphonesimulator13.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.1/builds/43)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2238)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2225)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2224)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2258)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2198)

2019-11-28 10:16 UTC, merged