[[ Bug 22616 ]] Fix incorrect placement of native layers within moved group
livecode/livecode pull request #7286
Opened 2020-03-10 12:38 UTC by livecodeian

This patch fixes bug 22616, where the native layer of a widget within a group
would be offset incorrectly from the parent layer when the group was moved.

This is due to position calculations being based on the rect of the parent
group, which was not updated until after the native layer of the widget was
repositioned, so the new position of the layer was based on the old position
of its container rather than the updated position.

2020-03-12 12:38 UTC, runrevmark requested changes

2020-03-12 12:38 UTC, runrevmark commented on engine/src/group.cpp
> +			// Make sure group rect is updated before moving child controls
I suggest:
```
/* Make sure we update the group rect before the child controls. This
 * is to ensure any native layers can fetch the correct rect to compute
 * their relative location. */
```
(Or something similar if that is not 100% accurate).

2020-03-13 08:21 UTC, runrevmark commented
@livecode-vulcan review ok 472ae14

2020-03-13 08:22 UTC, livecode-vulcan commented
💙 review by @runrevmark ok 472ae146586f33bcf5c670eef8ac00afc145b71e

2020-03-13 09:01 UTC, livecode-vulcan commented
😎 test success 472ae146586f33bcf5c670eef8ac00afc145b71e

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/733)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/142)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/142)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/142)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/142)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2259)
* try-community-universal-ios-iphoneos13.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.2/builds/34)
* try-community-universal-ios-iphonesimulator13.2: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.2/builds/34)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2288)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2275)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2274)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2308)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2248)

2020-03-13 14:27 UTC, merged