[[ Bug 22645 ]] Add NSBluetoothAlwaysUsageDescription to iOS plist
livecode/livecode pull request #7306
Opened 2020-03-25 22:40 UTC by montegoulding

This patch adds the `NSBluetoothAlwaysUsageDescription` key and value to the
iOS template plist. If this key does not exist the application will crash
on iOS 13 when using bluetooth functions.

2020-04-01 08:37 UTC, runrevmark requested changes

2020-04-01 08:37 UTC, runrevmark commented on engine/rsrc/standalone-mobile-Info.plist
> +	<string>This application requires access to BlueTooth always</string>
`Bluetooth` not `BlueTooth`

2020-04-03 10:37 UTC, livecodepanos commented
@livecode-vulcan review ok 3a5585f

2020-04-03 10:40 UTC, livecode-vulcan commented
💙 review by @livecodepanos ok 3a5585f31b52cc960461f1d168867e5c3f4a934f

2020-04-03 11:06 UTC, livecode-vulcan commented
😎 test success 3a5585f31b52cc960461f1d168867e5c3f4a934f

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/751)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/160)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/160)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/160)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/160)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2277)
* try-community-universal-ios-iphoneos13.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.4/builds/11)
* try-community-universal-ios-iphonesimulator13.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.4/builds/11)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2306)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2293)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2292)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2327)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2267)

2020-04-03 11:06 UTC, merged