[[ Bug 22760 ]] Fix 'external' handler invocation
livecode/livecode pull request #7367
Opened 2020-06-02 01:26 UTC by montegoulding

This patch ensures that when a handler-ref is invoked from the main/ui thread
on mobile that a jump is made to the script/engine thread before being
executed.

After the handler is executed the JNI environment is reset for the calling
thread. This patch also fixes an issue where `MCJavaGetJObjectClassName` did
not call `MCJavaDoAttachCurrentThread` and therefore could access JNI
environment attached to a different thread.

(cherry picked from commit 15eff1554567cc63e5d6509b29201dc89d8ff20b)

2020-06-10 12:02 UTC, runrevmark requested changes
Can you remove the 'cherry pick' comment from the commit message please.

2020-06-10 12:02 UTC, runrevmark commented on docs/lcb/notes/22760.md
> +# LiveCode Builder Standard Library
I think this is more a bug fix note - we always were attempting to jump to an appropriate thread, it was just the *wrong* thread!

So I think this would be sufficient:
```
# LiveCode Build Standard Library

## Foreign function interface

# [ 22760 ] Handlers invoked by foreign code on mobile now run on the correct thread.
```

2020-06-11 10:14 UTC, runrevmark approved these changes

2020-06-11 10:14 UTC, runrevmark commented
@livecode-vulcan review ok 1f720fb

2020-06-11 14:42 UTC, livecode-vulcan commented
💙 review by @runrevmark ok 1f720fbc6788e72da66ff6229cf7581913fc575b

2020-06-11 17:07 UTC, livecode-vulcan commented
😎 test success 1f720fbc6788e72da66ff6229cf7581913fc575b

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/819)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/228)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/228)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/228)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/228)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2345)
* try-community-universal-ios-iphoneos13.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.4/builds/78)
* try-community-universal-ios-iphonesimulator13.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.4/builds/80)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2373)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2361)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2360)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2395)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2335)

2020-06-11 18:07 UTC, merged