[[ Bug 22777 ]] Implement hitTest in iOS native container view
livecode/livecode pull request #7373
Opened 2020-06-10 06:06 UTC by montegoulding

This patch implements a hit test in the iOS native container view so it does not
block events from underlying views. By returning `nil` if the event does not
hit a child view the remaining view hierarchy will be traversed to find the
correct target view.

2020-06-10 10:05 UTC, runrevmark requested changes

2020-06-10 10:05 UTC, runrevmark commented on engine/src/native-layer-ios.mm
> +	/* The container view should not trap any eveents so if the hitTest returns self we
`events`

2020-06-10 10:05 UTC, runrevmark commented on engine/src/native-layer-ios.mm
> +	if (t_hit_view == self) {
Braces go on separate lines.

2020-06-11 10:03 UTC, runrevmark commented
@livecode-vulcan review ok add896c

2020-06-11 10:12 UTC, runrevmark approved these changes

2020-06-11 10:54 UTC, livecodepanos commented
@livecode-vulcan review ok add896c

2020-06-11 10:58 UTC, livecodepanos commented
@livecode-vulcan retry add896c

2020-06-11 13:48 UTC, livecodepanos commented
@livecode-vulcan retry add896c

2020-06-11 14:25 UTC, livecode-vulcan commented
💙 review by @livecodepanos ok add896c2a20aecc734a6a86ab2d131c2d040c2c8

2020-06-11 16:31 UTC, livecode-vulcan commented
😎 test success add896c2a20aecc734a6a86ab2d131c2d040c2c8

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/818)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/227)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/227)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/227)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/227)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2344)
* try-community-universal-ios-iphoneos13.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.4/builds/77)
* try-community-universal-ios-iphonesimulator13.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.4/builds/79)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2372)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2360)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2359)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2394)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2334)

2020-06-11 18:16 UTC, merged