[21353] Ensure long lines are shown in full in mobilePick on iOS
livecode/livecode pull request #7375
Opened 2020-06-11 13:10 UTC by livecodepanos

Previously, if a line was too long, it was truncated at the end. Now, the text size of a long line will be reduced so as the line can fit the container of the picker wheel.

2020-07-02 10:17 UTC, runrevmark requested changes
The title of the commit message should use `[[ Bug 21353 ]]` as the prefix rather than `[21353]`

2020-07-03 12:21 UTC, runrevmark commented
@livecode-vulcan review ok e34596c

2020-07-03 12:31 UTC, livecode-vulcan commented
💙 review by @runrevmark ok e34596cc09ca486480fb2d55b2ea558a644d61c9

2020-07-03 13:43 UTC, livecode-vulcan commented
😎 test success e34596cc09ca486480fb2d55b2ea558a644d61c9

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/839)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/248)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/248)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/248)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/248)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2365)
* try-community-universal-ios-iphoneos13.5: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.5/builds/16)
* try-community-universal-ios-iphonesimulator13.5: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.5/builds/16)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2393)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2381)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2380)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2415)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2355)

2020-07-03 13:49 UTC, merged