[[ 22763 ]] Ensure the captured image is not rotated when saved.
livecode/livecode pull request #7398
Opened 2020-07-07 07:31 UTC by livecodepanos

2020-07-08 07:00 UTC, runrevmark requested changes
There's no need for the `.` at the end of the commit title. The commit message is empty.

2020-07-17 15:06 UTC, runrevmark commented
The commit title should begin with `[[ Bug 22763 ]]`

2020-07-17 15:06 UTC, runrevmark requested changes
See conversation comment

2020-07-20 06:40 UTC, runrevmark approved these changes

2020-07-20 06:40 UTC, runrevmark commented
@livecode-vulcan review ok 7a7e8ce

2020-07-20 06:43 UTC, livecode-vulcan commented
💙 review by @runrevmark ok 7a7e8ce7263e87f36d88bcd194ea8ad5542c9083

2020-07-20 07:16 UTC, livecode-vulcan commented
😎 test success 7a7e8ce7263e87f36d88bcd194ea8ad5542c9083

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/846)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/255)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/255)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/255)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/255)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2372)
* try-community-universal-ios-iphoneos13.5: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.5/builds/23)
* try-community-universal-ios-iphonesimulator13.5: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.5/builds/23)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2400)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2388)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2387)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2422)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2362)

2020-07-20 07:16 UTC, merged