Build with xcode 12
livecode/livecode pull request #7450
Opened 2020-10-13 13:01 UTC by livecodepanos

This patch addresses various errors when building with Xcode 12.

It needs https://github.com/livecode/livecode/pull/7449

2020-10-16 10:39 UTC, runrevmark requested changes
Can you file a BZ issue (in addition to the one for the change to GetSystemIdentifier) about 'update the engine to compile with Xcode 12). [ This aspect doesn't require a release note - but its useful to record the change as an issue in BZ ].

Can you also separate the commits so all tweaks to config/source to make things compile is one commit; and the change to mobileGetSystemIdentifier (or is it iphoneGetSystemIdentifier?) in another.

2020-10-16 10:39 UTC, runrevmark commented on engine/src/mbliphoneextra.mm
> +    return false;
This will cause an error to be thrown - we want to return empty:
```
{
    r_identifier = MCValueRetain(kMCEmptyString);
    return true;
}
```

2020-10-16 10:39 UTC, runrevmark commented on engine/src/mbliphoneextra.mm
> +    return false;
This also requires a distinct bug filed in LC and a release note added for it - e.g. `The long deprecated mobileGetSystemIdentifier command now returns empty.`

(I think thats the name of the command...)

2020-10-19 10:26 UTC, runrevmark requested changes
@livecodepanos As mentioned in the previous review, please file separate BZ's about both the xcode 12 update and the change to the iphoneSystemIdentifier - and add a release note for the latter. It is probably worth splitting into two PRs as well (as discussed offline).

2020-10-19 11:05 UTC, livecodepanos commented
@runrevmark 

BZ reports:

1. Update the engine to compile with Xcode 12: https://quality.livecode.com/show_bug.cgi?id=22946
2. Add release note for change of behavior of deprecated `iphoneSystemIdentifier`: https://quality.livecode.com/show_bug.cgi?id=22947

Release note PR for `iphoneSystemIdentifier`: https://github.com/livecode/livecode/pull/7456

2020-10-22 14:40 UTC, runrevmark requested changes
Can you tweak the commit message title so that it is:
```
[[ Bug 22946 ]] Update the engine to compile with Xcode 12
```

2020-10-22 15:30 UTC, livecodepanos commented
@runrevmark Done :)

2020-10-22 16:00 UTC, runrevmark approved these changes

2020-10-22 16:00 UTC, runrevmark commented
@livecode-vulcan review ok 54489a1

2020-10-22 16:01 UTC, livecode-vulcan commented
💙 review by @runrevmark ok 54489a1501b4a4df362b6d029685ba792dbd6e0a

2020-10-22 16:31 UTC, livecode-vulcan commented
😎 test success 54489a1501b4a4df362b6d029685ba792dbd6e0a

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/898)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/307)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/307)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/307)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/307)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2424)
* try-community-universal-ios-iphoneos14.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos14.1/builds/1)
* try-community-universal-ios-iphoneos13.5: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.5/builds/77)
* try-community-universal-ios-iphonesimulator14.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator14.1/builds/1)
* try-community-universal-ios-iphonesimulator13.5: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.5/builds/73)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2451)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2440)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2439)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2474)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2414)

2020-10-22 17:39 UTC, livecodepanos commented
Trying again with Xcode 12.x:

@livecode-vulcan retry 54489a1

2020-10-22 18:13 UTC, livecode-vulcan commented
😎 test success 54489a1501b4a4df362b6d029685ba792dbd6e0a

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/899)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/308)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/308)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/308)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/308)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2425)
* try-community-universal-ios-iphoneos14.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos14.1/builds/2)
* try-community-universal-ios-iphoneos13.5: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos13.5/builds/78)
* try-community-universal-ios-iphonesimulator14.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator14.1/builds/2)
* try-community-universal-ios-iphonesimulator13.5: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator13.5/builds/74)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2452)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2441)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2440)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2475)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2415)

2020-10-22 18:59 UTC, merged