[[ Bug 22365 ]] Fix Accelerated rendering glitch when multiple stacks are open
livecode/livecode pull request #7494
Opened 2020-12-23 16:17 UTC by livecodeian

This patch fixes a graphical glitch when updating the display when more than one stack is open and a non-visible stack requires a window update (such as being reshaped).

Fixes https://quality.livecode.com/show_bug.cgi?id=22365

2021-01-05 08:29 UTC, runrevmark requested changes

2021-01-05 08:29 UTC, runrevmark commented on docs/notes/bugfix-22365.md
> +# Fix black screen on Android when navigating between cards with accelerattedRendering enabled
`accelerated`

2021-02-15 10:50 UTC, livecodeian commented on docs/notes/bugfix-22365.md
> +# Fix black screen on Android when navigating between cards with accelerattedRendering enabled
@runrevmark Typo fixed

2021-02-15 11:11 UTC, runrevmark approved these changes

2021-02-15 11:11 UTC, runrevmark commented
@livecode-vulcan review ok d1f6186

2021-02-15 11:15 UTC, livecode-vulcan commented
💙 review by @runrevmark ok d1f618600afb7760f1cb7188ad8d905d2156484c

2021-02-15 12:09 UTC, livecode-vulcan commented
😎 test success d1f618600afb7760f1cb7188ad8d905d2156484c

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/960)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/368)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/367)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/366)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/367)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2485)
* try-community-universal-ios-iphoneos14.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos14.4/builds/14)
* try-community-universal-ios-iphoneos14.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos14.1/builds/63)
* try-community-universal-ios-iphonesimulator14.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator14.4/builds/14)
* try-community-universal-ios-iphonesimulator14.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator14.1/builds/61)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2512)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2501)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2499)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2536)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2472)

2021-02-15 12:54 UTC, merged