[[ Bug 23075 ]] Process events while waiting in a modal session on Macos
livecode/livecode pull request #7517
Opened 2021-02-03 16:59 UTC by livecodeian

This patch fixes bug 23075 where a sheet launched from a modal stack
would not respond to user input on Macos. This was due to events not
being processed while waiting in a modal session.

Fixes https://quality.livecode.com/show_bug.cgi?id=23075

2021-02-03 17:18 UTC, livecodepanos commented
@livecodeian I think this needs to be rebased against `release-9.6.2`

2021-02-04 08:49 UTC, runrevmark approved these changes

2021-02-04 08:49 UTC, runrevmark requested changes
As panos mentioned this needs rebased on release-9.6.2 :)

2021-02-04 11:26 UTC, livecodeian commented
@runrevmark rebased and retargetted to release-9.6.2

2021-02-04 14:02 UTC, runrevmark approved these changes

2021-02-04 14:02 UTC, runrevmark commented
@livecode-vulcan review ok fd71fea

2021-02-04 14:04 UTC, livecode-vulcan commented
💙 review by @runrevmark ok fd71fea7924fe2ef3de95b37666aa4d5482ee139

2021-02-04 14:31 UTC, livecode-vulcan commented
😎 test success fd71fea7924fe2ef3de95b37666aa4d5482ee139

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/950)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/358)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/357)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/356)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/357)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2475)
* try-community-universal-ios-iphoneos14.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos14.4/builds/4)
* try-community-universal-ios-iphoneos14.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos14.1/builds/53)
* try-community-universal-ios-iphonesimulator14.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator14.4/builds/4)
* try-community-universal-ios-iphonesimulator14.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator14.1/builds/51)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2502)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2491)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2489)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2526)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2462)

2021-02-04 14:33 UTC, merged