[[ Bug 16745 ]] Fix $_POST_RAW on Windows Server
livecode/livecode pull request #7518
Opened 2021-02-05 10:13 UTC by montegoulding

This patch fixes an issue where `$_POST_RAW` was not set if posted data
was too large to be buffered. The issue was caused by:

* When a file was created for caching the post data it was using `OpenFd`
which only supports the stdio handles on Windows.
* When reading from the cache we need to iterate until the read either
fails or completes the required read length.

2021-04-23 08:32 UTC, runrevmark requested changes
Heh - so it took me a while to figure out what was going on here re the OpenFd stuff :)

OpenFd is used in very few places - its used to wrap a temporary file fd on linux, and to wrap the standard i/o onall platforms.

My suggestion would be to change OpenFd to take a uintptr_t as its 'fd' argument. Then this is used for FILEHANDLEs on Windows, but actual fds on the other platforms. This would just be a signature change on all platforms but windows.

On Windows, we need to change the IO_stdin* inits to pass in the actual std handle (which is what GetStdHandle returns); then update the use of it in the current place changed to MCS_take_file_handle...

Of course, having just looked at MCS_create_temporary_file - why are we using CreateFile direct? Can we not just use MCsystem->OpenFile() direct? (If we can then that's all we need to change - apart from the buffering loop addition :) )

2021-04-28 10:07 UTC, runrevmark requested changes

2021-04-28 10:07 UTC, runrevmark commented on engine/src/srvwindows.cpp
> +		r_name_string = MCValueRetain(*t_temp_file);
You can do:
```
r_name_string = t_temp_file.Take();
```

2021-04-29 03:08 UTC, montegoulding commented on engine/src/srvwindows.cpp
> +		r_name_string = MCValueRetain(*t_temp_file);
aha, forgot about that!

2021-06-09 09:13 UTC, runrevmark approved these changes

2021-06-09 09:14 UTC, runrevmark commented
@livecode-vulcan review ok 7f49088

2021-06-09 09:16 UTC, livecode-vulcan commented
💙 review by @runrevmark ok 7f49088de2f94fcde751aee71d7f06610c831927

2021-06-09 09:52 UTC, livecode-vulcan commented
😎 test success 7f49088de2f94fcde751aee71d7f06610c831927

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/1032)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/440)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/439)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/438)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/439)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2557)
* try-community-universal-ios-iphoneos14.5: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos14.5/builds/34)
* try-community-universal-ios-iphoneos14.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos14.4/builds/86)
* try-community-universal-ios-iphonesimulator14.5: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator14.5/builds/34)
* try-community-universal-ios-iphonesimulator14.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator14.4/builds/85)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2583)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2573)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2571)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2608)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2544)

2021-06-09 10:10 UTC, merged