[[ Bug 23166 ]] Fix memory leak when parsing visual effect parameters
livecode/livecode pull request #7551
Opened 2021-04-15 14:52 UTC by livecodeian

This patch fixes a memory leak when parsing visual effects, due to an
unreleased array used to hold effect parameters

Fixes https://quality.livecode.com/show_bug.cgi?id=23166

2021-04-16 08:26 UTC, livecodepanos commented
@livecodeian I _think_ this needs to be rebased onto `develop-9.6`

2021-04-21 10:07 UTC, runrevmark requested changes
Can you rebase on develop-9.6 please :)

2021-04-23 08:34 UTC, runrevmark approved these changes

2021-04-23 08:34 UTC, runrevmark commented
@livecode-vulcan review ok 985a7b4

2021-04-23 08:36 UTC, livecode-vulcan commented
💙 review by @runrevmark ok 985a7b46dd958a474fe1d537b98fcfae6686ebda

2021-04-23 09:01 UTC, livecode-vulcan commented
😎 test success 985a7b46dd958a474fe1d537b98fcfae6686ebda

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/988)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/396)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/395)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/394)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/395)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2513)
* try-community-universal-ios-iphoneos14.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos14.4/builds/42)
* try-community-universal-ios-iphoneos14.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos14.1/builds/91)
* try-community-universal-ios-iphonesimulator14.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator14.4/builds/42)
* try-community-universal-ios-iphonesimulator14.1: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator14.1/builds/89)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2540)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2529)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2527)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2564)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2500)

2021-04-23 11:52 UTC, merged