[[ Bug 22791 ]] Fix error signing Mac standalones when app name contains accents
livecode/livecode pull request #7586
Opened 2021-06-18 15:04 UTC by livecodeian

This patch fixes an error when using the codesign utility to sign Mac
standalones, when the app name contains accented characters. This is
due to codesign expecting unicode characters in the plist to be given
in decomposed form.

Fixes https://quality.livecode.com/show_bug.cgi?id=22791

2021-06-18 15:12 UTC, runrevmark requested changes
@livecodeian Can you target this as develop-9.6 as it should go into 9.6.3

2021-06-18 15:26 UTC, livecodeian commented
@runrevmark I've rebased and retargetted this to develop-9.6

2021-06-30 07:02 UTC, runrevmark approved these changes

2021-06-30 07:03 UTC, runrevmark commented
@livecode-vulcan review ok 31acf8e

2021-06-30 07:05 UTC, livecode-vulcan commented
💙 review by @runrevmark ok 31acf8e6a7814a26f592ff6dd5c5e0a3592e7932

2021-06-30 07:42 UTC, livecode-vulcan commented
😎 test success 31acf8e6a7814a26f592ff6dd5c5e0a3592e7932

* try-community-armv6-android-sdk26_ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv6-android-sdk26_ndk16r15/builds/1040)
* try-community-armv7-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-armv7-android-ndk16r15/builds/448)
* try-community-arm64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-arm64-android-ndk16r15/builds/447)
* try-community-x86-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86-android-ndk16r15/builds/446)
* try-community-x86_64-android-ndk16r15: [success](https://vulcan.livecode.com/builders/try-community-x86_64-android-ndk16r15/builds/447)
* try-community-js-emscripten-sdk1.35: [success](https://vulcan.livecode.com/builders/try-community-js-emscripten-sdk1.35/builds/2565)
* try-community-universal-ios-iphoneos14.5: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos14.5/builds/42)
* try-community-universal-ios-iphoneos14.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphoneos14.4/builds/94)
* try-community-universal-ios-iphonesimulator14.5: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator14.5/builds/42)
* try-community-universal-ios-iphonesimulator14.4: [success](https://vulcan.livecode.com/builders/try-community-universal-ios-iphonesimulator14.4/builds/93)
* try-community-universal-mac-macosx10.9: [success](https://vulcan.livecode.com/builders/try-community-universal-mac-macosx10.9/builds/2591)
* try-community-x86-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86-linux-debian8/builds/2581)
* try-community-x86_64-linux-debian8: [success](https://vulcan.livecode.com/builders/try-community-x86_64-linux-debian8/builds/2579)
* try-community-x86-win32: [success](https://vulcan.livecode.com/builders/try-community-x86-win32/builds/2616)
* try-community-x86_64-win32: [success](https://vulcan.livecode.com/builders/try-community-x86_64-win32/builds/2552)

2021-06-30 07:46 UTC, merged